# ── Build stage: install dependencies ────────────────────────────────
FROM python:3.11-slim AS builder

WORKDIR /app

# System libs needed by some Python packages (e.g. grpcio, scipy)
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt


# ── Runtime stage ─────────────────────────────────────────────────────
FROM python:3.11-slim AS runtime

WORKDIR /app

# Copy installed packages from builder
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Application source
COPY src/       ./src/
COPY frontend/  ./frontend/

# Pre-computed pipeline artifacts (generated by python main.py locally)
COPY data/      ./data/
COPY reports/   ./reports/

# Cloud Run injects PORT; default to 8080 if missing
ENV PORT=8080
EXPOSE 8080

# Vertex AI project/location — override at deploy time via --set-env-vars
ENV GOOGLE_CLOUD_LOCATION=us-central1

# Use shell form so $PORT is expanded at runtime
CMD uvicorn src.api:app --host 0.0.0.0 --port $PORT --workers 1
